# Generated by Django 3.2.8 on 2021-10-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100, unique=True)),
                ('colour', models.CharField(max_length=100)),
                ('storage', models.PositiveIntegerField(max_length=3)),
                ('copies', models.PositiveIntegerField(max_length=100)),
                ('price', models.PositiveIntegerField(default=100, max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
